//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPMRVPark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basket
    {
        public Basket()
        {
            this.BasketItems = new HashSet<BasketItem>();
        }
    
        public string BasketID { get; set; }
        public System.DateTime OrderDate { get; set; }
    
        public virtual ICollection<BasketItem> BasketItems { get; set; }
    }
}
